Repository 24AWP-FAVICON/backend, pull requests merged in 2024-05, with the labels that each got.

#4 Feature/#3 login,join
  src/main/java/com/example/demo/config/RedisConfig.java
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/config/SwaggerConfig.java
  src/main/java/com/example/demo/controller/JwtController.java
  src/main/java/com/example/demo/dto/oauth2/CustomOAuth2User.java
  src/main/java/com/example/demo/dto/oauth2/GoogleOAuth2DTO.java
  src/main/java/com/example/demo/dto/oauth2/JoinGoogleUserDTO.java
  src/main/java/com/example/demo/dto/oauth2/OAuth2DTO.java
  src/main/java/com/example/demo/entity/Role.java
  src/main/java/com/example/demo/entity/User.java
  src/main/java/com/example/demo/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/demo/repository/UserRepository.java
  src/main/java/com/example/demo/service/CustomOAuth2UserService.java
  src/main/java/com/example/demo/service/GoogleJoinService.java
  src/main/java/com/example/demo/service/JwtUtil.java
  src/main/java/com/example/demo/service/RedisUtil.java
  src/main/java/com/example/demo/service/UserCleanupScheduler.java
  src/test/java/com/example/demo/DemoApplicationTests.java
Labels: enhancement

#6 Feature/#2 trip planner
  build.gradle
  gradlew
  src/main/java/com/example/demo/controller/TripController.java
  src/main/java/com/example/demo/dto/planner/AccommodationDetailsDTO.java
  src/main/java/com/example/demo/dto/planner/LocationDetailsDTO.java
  src/main/java/com/example/demo/dto/planner/TripCreationDTO.java
  src/main/java/com/example/demo/dto/planner/TripDateDetailsDTO.java
  src/main/java/com/example/demo/dto/planner/TripDateResponseDTO.java
  src/main/java/com/example/demo/dto/planner/TripPatchDTO.java
  src/main/java/com/example/demo/dto/planner/UserIdsDTO.java
  src/main/java/com/example/demo/entity/Accommodation.java
  src/main/java/com/example/demo/entity/Location.java
  src/main/java/com/example/demo/entity/Memo.java
  src/main/java/com/example/demo/entity/Trip.java
  src/main/java/com/example/demo/entity/TripDate.java
  src/main/java/com/example/demo/entity/User.java
  src/main/java/com/example/demo/repository/AccommodationRepository.java
  src/main/java/com/example/demo/repository/LocationRepository.java
  src/main/java/com/example/demo/repository/MemoRepository.java
  src/main/java/com/example/demo/repository/TripDateRepository.java
  src/main/java/com/example/demo/repository/TripRepository.java
  src/main/java/com/example/demo/repository/UserRepository.java
  src/test/java/com/example/demo/DemoApplicationTests.java
Labels: enhancement

#9 Refactoring/logout and exception
  src/main/java/com/example/demo/exception/ComponentNotFoundException.java
  src/main/java/com/example/demo/exception/GlobalExceptionHandler.java
  src/main/java/com/example/demo/exception/TokenExpiredException.java
  src/main/java/com/example/demo/exception/TokenInvalidException.java
  src/main/java/com/example/demo/exception/UnAuthorizedUserException.java
  src/main/java/com/example/demo/filter/CustomLogoutFilter.java
  src/main/java/com/example/demo/service/JwtCheckService.java
Labels: enhancement

#11 Feature/#8 post service
  build.gradle
  src/main/java/com/example/demo/config/S3Config.java
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/controller/CommentController.java
  src/main/java/com/example/demo/controller/JwtController.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/controller/TripController.java
  src/main/java/com/example/demo/dto/comment/CommentDto.java
  src/main/java/com/example/demo/dto/comment/CommentRequestDto.java
  src/main/java/com/example/demo/dto/comment/CommentResponseDto.java
  src/main/java/com/example/demo/dto/like/PostLikeResponseDto.java
  src/main/java/com/example/demo/dto/post/PostCreateDto.java
  src/main/java/com/example/demo/dto/post/PostResponseDto.java
  src/main/java/com/example/demo/dto/post/PostUpdateDto.java
  src/main/java/com/example/demo/dto/view/ViewResponseDto.java
  src/main/java/com/example/demo/entity/Attachment.java
  src/main/java/com/example/demo/entity/Comment.java
  src/main/java/com/example/demo/entity/Post.java
  src/main/java/com/example/demo/entity/PostLike.java
  src/main/java/com/example/demo/entity/User.java
  src/main/java/com/example/demo/entity/View.java
  src/main/java/com/example/demo/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/demo/repository/AttachmentFileRepository.java
  src/main/java/com/example/demo/repository/CommentRepository.java
  src/main/java/com/example/demo/repository/PostLikeRepository.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/repository/UserRepository.java
  src/main/java/com/example/demo/service/AttachmentFileService.java
  src/main/java/com/example/demo/service/CommentService.java
  src/main/java/com/example/demo/service/GoogleJoinService.java
  src/main/java/com/example/demo/service/PostService.java
  src/main/java/com/example/demo/service/S3ImageService.java
  src/main/java/com/example/demo/service/UserCleanupScheduler.java
Labels: enhancement

#16 #15 - feat: 회원탈퇴, 정보조회 등 UserService 남은 부분 구현
  src/main/java/com/example/demo/controller/user/AlarmController.java
  src/main/java/com/example/demo/controller/user/UserController.java
  src/main/java/com/example/demo/dto/users/user/UserInfoDto.java
  src/main/java/com/example/demo/service/users/user/UserService.java
  src/test/java/com/example/demo/service/PostServiceTest.java
  src/test/java/com/example/demo/service/S3ImageServiceTest.java
Labels: enhancement

#17 Feature/#5 messenger (+ Bugfix)
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/example/demo/config/WebSocketConfig.java
  src/main/java/com/example/demo/config/WebSocketEventListener.java
  src/main/java/com/example/demo/controller/messenger/ChatRoomController.java
  src/main/java/com/example/demo/controller/messenger/MessageController.java
  src/main/java/com/example/demo/controller/trip/TripController.java
  src/main/java/com/example/demo/dto/messenger/ChatMessageDTO.java
  src/main/java/com/example/demo/dto/messenger/ChatRoomRequestDTO.java
  src/main/java/com/example/demo/dto/messenger/ChatRoomResponseDTO.java
  src/main/java/com/example/demo/entity/messenger/ChatJoin.java
  src/main/java/com/example/demo/entity/messenger/ChatJoinId.java
  src/main/java/com/example/demo/entity/messenger/ChatMessage.java
  src/main/java/com/example/demo/entity/messenger/ChatRoom.java
  src/main/java/com/example/demo/entity/messenger/Message.java
  src/main/java/com/example/demo/entity/messenger/UnreadMember.java
  src/main/java/com/example/demo/entity/messenger/UnreadMemberId.java
  src/main/java/com/example/demo/entity/planner/Accommodation.java
  src/main/java/com/example/demo/entity/planner/Location.java
  src/main/java/com/example/demo/entity/planner/Memo.java
  src/main/java/com/example/demo/entity/planner/Trip.java
  src/main/java/com/example/demo/entity/planner/TripDate.java
  src/main/java/com/example/demo/entity/users/user/User.java
  src/main/java/com/example/demo/repository/messenger/ChatJoinRepository.java
  src/main/java/com/example/demo/repository/messenger/ChatMessageRepository.java
  src/main/java/com/example/demo/repository/messenger/ChatRoomRepository.java
  src/main/java/com/example/demo/repository/messenger/UnreadMemberRepository.java
  src/main/java/com/example/demo/service/messenger/ChatMessageService.java
  src/main/java/com/example/demo/service/messenger/ChatRoomService.java
  src/main/resources/static/css/main.css
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
Labels: bug, enhancement

#18 fix - login에서 axios 사용시 XmlHttpRequest 임시 해결
  src/main/java/com/example/demo/entity/users/user/User.java
  src/main/java/com/example/demo/handler/OAuth2SuccessHandler.java
Labels: bug
