Repository 24AWP-FAVICON/backend, pull requests merged in 2024-10, with the labels that each got.

#32 Refact/#29. 여행 계획 관련 기능 리팩토링
  .DS_Store
  .github/pull_request_template.md
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/example/demo/controller/planner/TripDatePlannerController.java
  src/main/java/com/example/demo/controller/planner/TripPlannerController.java
  src/main/java/com/example/demo/controller/trip/TripController.java
  src/main/java/com/example/demo/dto/planner/AccommodationDetailsDTO.java
  src/main/java/com/example/demo/dto/planner/LocationDetailsDTO.java
  src/main/java/com/example/demo/dto/planner/TripDateDetailsDTO.java
  src/main/java/com/example/demo/dto/planner/TripDateResponseDTO.java
  src/main/java/com/example/demo/dto/planner/TripPatchDTO.java
  src/main/java/com/example/demo/dto/planner/trip/TripRequestDTO.java
  src/main/java/com/example/demo/dto/planner/trip/TripResponseDTO.java
  src/main/java/com/example/demo/dto/planner/tripDate/AccommodationRequestDTO.java
  src/main/java/com/example/demo/dto/planner/tripDate/AccommodationResponseDTO.java
  src/main/java/com/example/demo/dto/planner/tripDate/LocationRequestDTO.java
  src/main/java/com/example/demo/dto/planner/tripDate/LocationResponseDTO.java
  src/main/java/com/example/demo/dto/planner/tripDate/TripDateRequestDTO.java
  src/main/java/com/example/demo/dto/planner/tripDate/TripDateResponseDTO.java
  src/main/java/com/example/demo/exception/InvalidUserException.java
  src/main/java/com/example/demo/repository/planner/LocationRepository.java
  src/main/java/com/example/demo/service/planner/TripDateNotFoundException.java
  src/main/java/com/example/demo/service/planner/TripDatePlannerService.java
  src/main/java/com/example/demo/service/planner/TripNotFoundException.java
  src/main/java/com/example/demo/service/planner/TripPlannerService.java
  src/main/resources/.DS_Store
  src/main/resources/static/.DS_Store
Labels: refactoring

#35 #30-refactor: WebSocket 메세지 처리 로직을 WebSocketMessageHandler로 분리
  src/main/java/com/example/demo/controller/planner/TripDatePlannerController.java
  src/main/java/com/example/demo/dto/planner/tripDate/TripDateRequestDTO.java
  src/main/java/com/example/demo/entity/planner/Accommodation.java
  src/main/java/com/example/demo/service/planner/TripDatePlannerService.java
  src/main/java/com/example/demo/websocket/config/WebSocketConfig.java
Labels: refactoring

#36 Refact/#31. 여행 계획 서비스 리팩토링 고도화
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/example/demo/controller/messenger/MessageController.java
  src/main/java/com/example/demo/controller/planner/TripDatePlannerController.java
  src/main/java/com/example/demo/controller/planner/TripPlannerController.java
  src/main/java/com/example/demo/converter/DtoConverter.java
  src/main/java/com/example/demo/service/planner/ComponentNotFoundException.java
  src/main/java/com/example/demo/service/planner/TripDateNotFoundException.java
  src/main/java/com/example/demo/service/planner/TripDatePlannerService.java
  src/main/java/com/example/demo/service/planner/TripNotFoundException.java
  src/main/java/com/example/demo/service/planner/TripPlannerService.java
  src/main/java/com/example/demo/websocket/WebSocketMessageHandler.java
Labels: refactoring

#37 Refactor/#34 Spring Security 고도화, git history 정리, java doc style 주석 추가
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/controller/JwtController.java
  src/main/java/com/example/demo/controller/community/CommentController.java
  src/main/java/com/example/demo/controller/community/CommunityController.java
  src/main/java/com/example/demo/controller/community/PostController.java
  src/main/java/com/example/demo/controller/messenger/ChatRoomController.java
  src/main/java/com/example/demo/controller/messenger/MessageController.java
  src/main/java/com/example/demo/controller/planner/TripDatePlannerController.java
  src/main/java/com/example/demo/controller/planner/TripPlannerController.java
  src/main/java/com/example/demo/controller/user/AlarmController.java
  src/main/java/com/example/demo/controller/user/UserController.java
  src/main/java/com/example/demo/dto/users/user/UserInfoDto.java
  src/main/java/com/example/demo/entity/community/block/Block.java
  src/main/java/com/example/demo/entity/community/comment/Comment.java
  src/main/java/com/example/demo/entity/community/follow/Follow.java
  src/main/java/com/example/demo/entity/community/post/Attachment.java
  src/main/java/com/example/demo/entity/community/post/Post.java
  src/main/java/com/example/demo/entity/community/post/PostLike.java
  src/main/java/com/example/demo/entity/community/post/View.java
  src/main/java/com/example/demo/entity/users/Alarm/AlarmEntity.java
  src/main/java/com/example/demo/entity/users/Alarm/AlarmSettings.java
  src/main/java/com/example/demo/entity/users/user/User.java
  src/main/java/com/example/demo/exception/GlobalExceptionHandler.java
  src/main/java/com/example/demo/filter/CustomLogoutFilter.java
  src/main/java/com/example/demo/filter/JwtExceptionFilter.java
  src/main/java/com/example/demo/filter/JwtFilter.java
  src/main/java/com/example/demo/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/demo/service/RedisUtil.java
  src/main/java/com/example/demo/service/community/comment/CommentService.java
  src/main/java/com/example/demo/service/community/community/CommunityService.java
  src/main/java/com/example/demo/service/community/post/AttachmentFileService.java
  src/main/java/com/example/demo/service/community/post/PostService.java
  src/main/java/com/example/demo/service/community/post/S3ImageService.java
  src/main/java/com/example/demo/service/jwt/JwtCheckService.java
  src/main/java/com/example/demo/service/jwt/JwtUtil.java
  src/main/java/com/example/demo/service/users/alarm/AlarmService.java
  src/main/java/com/example/demo/service/users/user/CustomOAuth2UserService.java
  src/main/java/com/example/demo/service/users/user/GoogleJoinService.java
  src/main/java/com/example/demo/service/users/user/UserCleanupScheduler.java
  src/main/java/com/example/demo/service/users/user/UserService.java
Labels: refactoring

#38 Test/#33. 여행 계획 & 메신저 기능 단위 테스트
  build.gradle
  src/main/java/com/example/demo/controller/messenger/ChatRoomController.java
  src/main/java/com/example/demo/controller/messenger/MessageController.java
  src/main/java/com/example/demo/controller/planner/TripDatePlannerController.java
  src/main/java/com/example/demo/controller/planner/TripPlannerController.java
  src/main/java/com/example/demo/dto/messenger/ChatRoomRequestDTO.java
  src/main/java/com/example/demo/entity/messenger/ChatMessage.java
  src/main/java/com/example/demo/entity/planner/Accommodation.java
  src/main/java/com/example/demo/entity/planner/Memo.java
  src/main/java/com/example/demo/repository/planner/MemoRepository.java
  src/main/java/com/example/demo/service/messenger/ChatMessageService.java
  src/main/java/com/example/demo/service/messenger/ChatRoomService.java
  src/main/java/com/example/demo/service/planner/TripDatePlannerService.java
  src/main/java/com/example/demo/websocket/WebSocketMessageHandler.java
  src/main/java/com/example/demo/websocket/config/WebSocketConfig.java
  src/test/java/com/example/demo/controller/messenger/ChatRoomControllerTest.java
  src/test/java/com/example/demo/controller/messenger/MessageControllerTest.java
  src/test/java/com/example/demo/controller/planner/TripDatePlannerControllerTest.java
  src/test/java/com/example/demo/controller/planner/TripPlannerControllerTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
  src/test/java/com/example/demo/service/S3ImageServiceTest.java
  src/test/java/com/example/demo/service/messenger/ChatMessageServiceTest.java
  src/test/java/com/example/demo/service/messenger/ChatRoomServiceTest.java
  src/test/java/com/example/demo/service/planner/TripDatePlannerServiceTest.java
  src/test/java/com/example/demo/service/planner/TripServiceTest.java
  src/test/java/com/example/demo/websocket/WebSocketMessageHandlerTest.java
Labels: test code

#39 Hotfix: 배포 위해 URL 환경 변수화 & 웹소켓 관련 에러 해결
  .github/workflows/gradle.yml
  .gitignore
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/filter/JwtFilter.java
  src/main/java/com/example/demo/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/demo/websocket/config/WebSocketConfig.java
Labels: HotFix
